# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Raghuveer
author:
  name: Raghuveer
  url: "https://nraghuveer.github.io"
url: "https://nraghuveer.github.io"
email: raghuveernaraharisetti@gmail.com
description: >
  Collection of musing and ramblings
baseurl: "" # the subpath of your site, e.g. /blog
repository: nraghuveer/nraghuveer.github.io

remote_theme: fongandrew/hydeout

disqus:
  shortname: "blog-nraghuveer-githubio"
# google_analytics: "UA-119528295-1"

twitter:
  username: raghu_veerN
  card: summary

github:
  username: nraghuveer

linkedin:
  username: nraghuveer

social:
  name: Raghuveer Naraharisetti
  username: nraghuveer
  links:
    - https://twitter.com/raghu_veerN
    - https://github.com/nraghuveer
    - https://linkedin.com/in/nraghuveer

# Dirs
layout_dir: _layouts
posts_dir: _posts

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - jekyll-github-metadata
  - jekyll-redirect-from
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
paginate: 5
paginate_path: "/blog/page:num"
permalink: /blog/:categories/:year/:month/:day/:title:output_ext

feed:
  path: /blog/feed.xml

# Sidebar link settings
sidebar_home_link: true
sidebar_blog_link: "/blog" # By default, your home page is your blog
# page. If you change your paginate_path,
# set this to the root of the paginate_path
# to enable a separate blog link.
